import { useEffect, useRef, useState } from 'react';
import { site } from './data';

const image = (name: string) => `/images/${name}.webp`;
const booking = site.contact.whatsapp;
function Arrow({ down = false }: { down?: boolean }) { return <svg aria-hidden="true" className={down ? 'rotate-90' : ''} width="22" height="22" viewBox="0 0 24 24" fill="none"><path d="M4 12h15m-6-6 6 6-6 6" stroke="currentColor" strokeWidth="1.4" /></svg>; }
function Symbol({ type = 0, className = '' }: { type?: number; className?: string }) {
 return <svg className={className} viewBox="0 0 120 120" fill="none" stroke="currentColor" strokeWidth="1" aria-hidden="true">
 {type === 0 && <>{[0,30,60,90,120,150].map(angle => <ellipse key={angle} cx="60" cy="60" rx="18" ry="48" transform={`rotate(${angle} 60 60)`} />)}</>}
 {type === 1 && <>{[0,1,2,3,4].map(i=><ellipse key={i} cx="60" cy="60" rx={12+i*9} ry="44" transform="rotate(35 60 60)" />)}</>}
 {type === 2 && <>{[0,1,2,3,4].map(i=><path key={i} d={`M12 ${35+i*12}c24-50 48 50 96 0`} />)}</>}
 </svg>;
}
function BookingLink({ light = false, label = 'Prenota una lezione' }: { light?: boolean; label?: string }) { return <a className={`pill ${light?'pill-light':''}`} href={booking} target="_blank" rel="noopener noreferrer">{label}<span><Arrow /></span></a>; }
function Header({ home }: { home: boolean }) {
 const [open,setOpen]=useState(false);
 useEffect(()=>{const close=(e:KeyboardEvent)=>{if(e.key==='Escape'){setOpen(false);document.querySelector<HTMLButtonElement>('.menu-button')?.focus();}};window.addEventListener('keydown',close);return()=>window.removeEventListener('keydown',close);},[]);
 return <header className={`header ${!home?'header-inner-page':''}`}><a className="wordmark" href="/" aria-label="Harmonie — Home">harmonie<span>PILATES & WELLNESS</span></a><nav aria-label="Navigazione principale" className="desktop-nav"><a href="/#harmonie">Lo studio</a><a href="/#metodo">Il metodo</a><a href="/#lezioni">Le lezioni</a><a href="/#contatti">Contatti</a></nav><a className="nav-book" href={booking} target="_blank" rel="noopener noreferrer">Iniziamo <Arrow /></a><button className="menu-button" aria-label={open?'Chiudi menu':'Apri menu'} aria-expanded={open} aria-controls="mobile-menu" onClick={()=>setOpen(!open)}><span>{open?'Chiudi':'Menu'}</span><span aria-hidden="true">{open?'−':'+'}</span></button><nav id="mobile-menu" aria-label="Navigazione mobile" hidden={!open} className="mobile-menu">{site.navigation.map((item,i)=><a key={item.href} href={`/${item.href}`} onClick={()=>setOpen(false)}><small>0{i+1}</small>{item.label}<Arrow /></a>)}</nav></header>;
}
function Hero() {
 return <section className="hero" aria-labelledby="hero-title"><img className="hero-photo" src={image('chiara-manno')} width="756" height="1008" fetchPriority="high" alt="Chiara Manno pratica un esercizio di Pilates sulla spiaggia, davanti al mare"/><div className="hero-shade"/><div className="hero-content"><div className="hero-eyebrow"><span>AGIRA, SICILIA</span><span>PILATES • MOVIMENTO • EQUILIBRIO</span></div><h1 id="hero-title">Torna al corpo.<br /><em>Ritrova il tuo</em><br /><span>equilibrio.</span></h1><div className="hero-bottom"><div><p>Uno spazio per rallentare.<br />Un nuovo modo di sentirti.</p><BookingLink light /></div><a className="scroll-cue" href="#harmonie"><span>SCOPRI HARMONIE</span><span className="circle"><Arrow down /></span></a></div></div><div className="hero-index" aria-hidden="true">01 — IL TUO TEMPO, QUI.</div></section>;
}
function About() {
 return <section id="harmonie" className="about section-pad"><div className="wrap"><div className="section-meta"><span>01 / BENVENUTA IN HARMONIE</span><span>Peaceful mind, grateful heart</span></div><div className="manifesto"><Symbol className="manifesto-symbol"/><h2>Non serve andare lontano<br />{" "}per ritrovare <em>il proprio centro.</em></h2><p>Ad Agira, uno spazio dedicato al movimento consapevole.<br className="hidden md:block"/> Per ascoltare il corpo, esserci con la mente, stare bene insieme.</p></div><div className="about-grid"><figure className="studio-photo"><img src={image('harmonie-pilates-studio')} alt="Chiara Manno in equilibrio nella sala Harmonie, con gli attrezzi Pilates sullo sfondo" width="642" height="950" loading="lazy"/><figcaption>Il movimento. Il respiro. Tu.</figcaption></figure><div className="about-copy"><span className="kicker">IL VOLTO DI HARMONIE</span><h3>Piacere,<br />sono <em>Chiara.</em></h3><p>Ho creato Harmonie per chi desidera dedicare uno spazio al proprio benessere, in un ambiente professionale, attento e accogliente.</p><p>Ogni lezione è un invito a muoversi con consapevolezza, ascoltare il corpo e mantenere la mente presente.</p><div className="signature"><span>Chiara Manno</span><small>{site.professional.role}</small></div><div className="name-note"><span>har·mo·nie</span><p>Armonia, in francese. Equilibrio, bellezza e pace interiore: il senso di tutto quello che facciamo.</p></div></div></div></div></section>;
}
const principles=[{word:'Ascolta.',title:'Il respiro dà il ritmo.',text:'Respirazione, allineamento e attenzione accompagnano ogni esercizio. Un invito a essere presenti, un movimento alla volta.',label:'RESPIRO & CONSAPEVOLEZZA',symbol:2},{word:'Esplora.',title:'Il corpo trova spazio.',text:'La pratica lavora su flessibilità, coordinazione ed equilibrio, attraverso gesti precisi e progressivi.',label:'MOBILITÀ & EQUILIBRIO',symbol:1},{word:'Ritrovati.',title:'La forza incontra il controllo.',text:'Il centro del corpo partecipa al movimento. Qualità, controllo e fluidità sono al cuore del metodo Pilates.',label:'FORZA & CONTROLLO',symbol:0}];
function Method() {return <section id="metodo" className="method section-pad"><div className="wrap"><div className="section-meta"><span>02 / IL METODO PILATES</span><span>MOVIMENTO, CON INTENZIONE</span></div><div className="method-heading"><h2>Piccoli gesti.<br /><em>Una nuova presenza.</em></h2><p>Il Pilates unisce esercizio fisico e concentrazione. Sviluppato da Joseph Pilates, mette al centro il controllo del corpo e la qualità del movimento.</p></div><div className="method-stack">{principles.map((p,i)=><article key={p.word} className={`method-card method-card-${i}`} style={{'--card-index':i} as React.CSSProperties}><div className="card-top"><span>{p.label}</span><span>0{i+1} / 03</span></div><div className="method-card-main"><h3>{p.word}</h3><div className="symbol-placeholder" data-motion-slot={`method-${i}`}><Symbol type={p.symbol}/></div></div><div className="card-bottom"><h4>{p.title}</h4><p>{p.text}</p></div></article>)}</div></div></section>;}
function Lessons(){return <section id="lezioni" className="lessons section-pad"><div className="wrap"><div className="section-meta"><span>03 / IL TUO APPUNTAMENTO</span><span>ATTIVITÀ RISERVATE AI SOCI</span></div><div className="lesson-layout"><div className="lesson-number"><div>60<span>minuti</span></div><p>Il resto può aspettare.</p><Symbol type={1} className="lesson-symbol"/></div><div className="lesson-content"><h2>Fai spazio<br /><em>al tuo tempo.</em></h2><div className="lesson-line"><span>01</span><div><h3>Prenota il tuo posto</h3><p>{site.lesson.booking}</p></div><Arrow /></div><div className="lesson-line"><span>02</span><div><h3>Porta solo l’essenziale</h3><p>{site.lesson.clothing}</p></div></div><div className="lesson-line"><span>03</span><div><h3>Entra in Harmonie</h3><p>{site.lesson.membership}</p></div></div><BookingLink /></div></div></div></section>;}
function Schedule(){return <section id="orari" className="schedule section-pad"><div className="wrap schedule-layout"><div><span className="kicker">04 / CI VEDIAMO IN SALA</span><h2>Trova il tuo<br /><em>momento.</em></h2><p>Lezioni su prenotazione nelle fasce indicate.<br />Scrivici per concordare la partecipazione.</p><a className="text-link" href={booking} target="_blank" rel="noopener noreferrer">Chiedi disponibilità <Arrow /></a></div><div className="schedule-days">{site.schedule.map((day,i)=><div className="schedule-day" key={day.day}><span className="day-index">0{i+1}</span><div><h3>{day.day}</h3><div className="flex flex-wrap gap-x-8 gap-y-2">{day.slots.map(slot=><span key={slot}>{slot}</span>)}</div></div><Symbol type={i} /></div>)}<p className="schedule-note">Ogni incontro inizia da una prenotazione.</p></div></div></section>;}
function Contact(){return <section id="contatti" className="contact section-pad"><div className="wrap"><div className="section-meta"><span>05 / INIZIAMO DA QUI</span><span>AGIRA, ENNA</span></div><div className="contact-heading"><h2>Il prossimo passo?<br /><em>È per te.</em></h2><a className="contact-orbit" href={booking} target="_blank" rel="noopener noreferrer"><Arrow /><span>PARLIAMONE</span></a></div><div className="contact-grid"><div><span className="kicker">VIENI A TROVARCI</span><address>{site.address.street}<br />{site.address.postalCode} Agira (Enna)</address><p>{site.address.note}</p><a className="text-link" href={site.contact.maps} target="_blank" rel="noopener noreferrer">Apri in Google Maps <Arrow /></a></div><div><span className="kicker">RESTIAMO IN CONTATTO</span><a className="contact-phone" href={site.contact.phoneHref}>{site.contact.phoneDisplay}</a><a className="contact-email" href={`mailto:${site.contact.email}`}>{site.contact.email}</a><a className="text-link" href={booking} target="_blank" rel="noopener noreferrer">Scrivi su WhatsApp <Arrow /></a></div><img className="original-logo" src={image('harmoniewellness-logo')} alt="Marchio originale ASD Harmonie Pilates & Wellness" width="160" height="160" loading="lazy"/></div></div></section>;}
function Footer(){ return ( <footer className="footer"> <div className="wrap"> <div className="footer-word" aria-hidden="true">harmonie</div> <div className="footer-bottom"> <div className="footer-credits"> <span>© {new Date().getFullYear()} {site.name}</span> <span> Made with the ♥ by{' '} <a href="https://etanoox.me/" target="_blank" rel="noopener noreferrer"> Giuseppe Ricceri </a> </span> </div> <nav aria-label="Informazioni legali"> <a href="/privacy/">Privacy</a> <a href="/cookie-policy/">Cookie Policy</a> <a href="/#contenuto">Torna su ↑</a> </nav> </div> </div> </footer> ); }
function Legal({path}:{path:string}){const cookie=path==='/cookie-policy/';return <section className="legal wrap"><a className="text-link" href="/">← Torna a Harmonie</a><span className="kicker">INFORMAZIONI SUL SITO</span><h1>{cookie?'Cookie Policy':'Privacy Policy'}</h1><p>Aggiornamento: 21 settembre 2026</p>{cookie?<><p>Il sito non utilizza cookie analitici, pubblicitari o di profilazione e non integra servizi di tracciamento. Non viene quindi mostrato un banner di consenso.</p><h2>Cookie tecnici</h2><p>Il sito non imposta direttamente cookie. L’infrastruttura di hosting può utilizzare meccanismi tecnici necessari alla sicurezza e al funzionamento delle pagine.</p><h2>Collegamenti esterni</h2><p>WhatsApp e Google Maps sono semplici link. Le condizioni dei rispettivi servizi si applicano dopo che scegli di visitarli.</p><h2>Aggiornamenti</h2><p>L’eventuale introduzione di strumenti di tracciamento richiederà un aggiornamento di questa informativa e delle modalità di consenso prima dell’attivazione.</p></>:<><p>Questa informativa essenziale riguarda la navigazione su harmoniewellness.it. Il sito non include moduli di contatto, newsletter, account o strumenti di profilazione.</p><h2>Dati di navigazione</h2><p>L’infrastruttura tecnica può trattare indirizzo IP, data e ora, pagina richiesta e informazioni sul browser per erogare e proteggere il servizio.</p><h2>Contatti volontari</h2><p>I dati comunicati tramite telefono, email o WhatsApp sono utilizzati per rispondere alla richiesta e gestire l’eventuale prenotazione, attraverso il canale scelto e secondo le condizioni del relativo fornitore.</p><h2>Servizi esterni</h2><p>Non sono incorporati mappe, video o feed social. I link verso servizi esterni si attivano soltanto quando decidi di aprirli.</p><h2>Contatti privacy</h2><p>Puoi scrivere a <a href={`mailto:${site.contact.email}`}>{site.contact.email}</a>. I dati identificativi completi del titolare e i termini di conservazione specifici devono essere integrati quando forniti dall’associazione.</p></>}</section>;}
export default function App({ path = '/' }: { path?: string }) {
 const home=path==='/'; const known=home||path==='/privacy/'||path==='/cookie-policy/'; const root=useRef<HTMLDivElement>(null);
 useEffect(()=>{if(!home||!('IntersectionObserver' in window))return;const observer=new IntersectionObserver(entries=>{entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('in-view');observer.unobserve(entry.target);}});},{threshold:.08});root.current?.querySelectorAll('.manifesto,.about-grid,.method-heading,.lesson-layout,.schedule-layout,.contact-heading').forEach(el=>{el.classList.add('reveal');observer.observe(el);});return()=>observer.disconnect();},[home]);
 return <div ref={root}><a className="skip-link" href="#contenuto">Vai al contenuto</a><Header home={home}/><main id="contenuto" tabIndex={-1}>{home?<><Hero/><About/><Method/><Lessons/><Schedule/><Contact/></>:known?<Legal path={path}/>:<section className="legal wrap"><span className="kicker">404</span><h1>Ritroviamo<br /><em>la strada.</em></h1><p>Questa pagina non esiste.</p><a className="pill" href="/">Torna a Harmonie <Arrow /></a></section>}</main><Footer/></div>;
}
