import React from 'react';
import { createRoot, hydrateRoot } from 'react-dom/client';
import '@fontsource/dm-sans/latin-400.css';
import '@fontsource/dm-sans/latin-500.css';
import '@fontsource/cormorant-garamond/latin-400.css';
import '@fontsource/cormorant-garamond/latin-400-italic.css';
import './style.css';
import App from './App';
const root = document.getElementById('root')!;
const path=window.location.pathname==='/'?'/':window.location.pathname.replace(/\/$/,'')+'/';
const app=<React.StrictMode><App path={path}/></React.StrictMode>;
if(root.children.length > 0) hydrateRoot(root,app);else createRoot(root).render(app);
